"""empty message

Revision ID: 2f9e92ac58fb
Revises: 
Create Date: 2021-01-07 13:16:21.696281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9e92ac58fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=True),
    sa.Column('lastName', sa.String(length=40), nullable=True),
    sa.Column('isHost', sa.Boolean(), nullable=True),
    sa.Column('avatarUrl', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('boats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boat_type', sa.String(length=50), nullable=False),
    sa.Column('total_occupancy', sa.Integer(), nullable=False),
    sa.Column('total_bedrooms', sa.Integer(), nullable=False),
    sa.Column('total_bathrooms', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('has_tv', sa.Boolean(), nullable=False),
    sa.Column('has_kitchen', sa.Boolean(), nullable=False),
    sa.Column('has_air_con', sa.Boolean(), nullable=False),
    sa.Column('has_internet', sa.Boolean(), nullable=False),
    sa.Column('has_heating', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=60, scale=50), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=60, scale=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boats')
    op.drop_table('users')
    # ### end Alembic commands ###
