"""empty message

Revision ID: 4fa65d2472b5
Revises:
Create Date: 2021-01-05 20:57:09.132758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa65d2472b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashedPassword', sa.String(
                        length=255), nullable=False),
                    sa.Column('firstName', sa.String(
                        length=40), nullable=True),
                    sa.Column('lastName', sa.String(length=40), nullable=True),
                    sa.Column('isHost', sa.Boolean(), nullable=True),
                    sa.Column('avatarUrl', sa.String(
                        length=100), nullable=True),
                    sa.Column('bio', sa.String(length=255), nullable=True),
                    sa.Column('createdAt', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
