"""empty message

Revision ID: d573ed568a5c
Revises: 0b7e737154d9
Create Date: 2021-01-13 05:43:08.976861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd573ed568a5c'
down_revision = '0b7e737154d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('media_name', sa.String(length=255), nullable=False),
    sa.Column('boat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
